name: PlayerCoords
main: skyss0fly\PlayerCoords\Main
version: 1.0
api: 5.0.0
author: skyss0fly
description: A simple coordinates plugin
permissions:
  coords.use:
    default: false
commands:
coords:
description: use this to display your coordinates
default: false
