name: PlayerCoords
main: skyss0fly\PlayerCoords\Main
version: 1.0
api: 5.0.0
author: skyss0fly
description: A simple coordinates plugin
permissions:
  coords.use:
    default: op
commands:
  coords:
    description: use this to display your coords
    permission: coords.use
    default: false
  coordsadmin:
    description: [Admin] use this to setup the config part of the plugin
    permissions: coords.admin
    default: false
