name: PlayerCoords
main: skyss0fly\PlayerCoords\Main
version: 1.1.1
api: 6.0.0
author: skyss0fly
description: A simple coordinates plugin
permissions:
  coords.use:
    default: op
commands:
  coords:
    description: use this to display your coords
    permission: coords.use
    default: false
  
